name: MirrorBot Environment

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  GitHubMail: ${{ secrets.GitHubMail }}
  GitHubName: ${{ secrets.GitHubName }} 
  BRANCH: "#2"

jobs:
  debug:
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: macOS Cleanup
        # This takes much more time than that of Ubuntu
        uses: rokibhasansagar/slimhub_actions@mac

      - name: Setup docker
        run: |
          brew install --cask virtualbox
          brew install --formula docker docker-machine

      - name: Setup VM
        run: |
          curl -sL https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso -o ~/Downloads/boot2docker.iso
          docker-machine create -d virtualbox --virtualbox-disk-size=300000 --virtualbox-memory=8096 --virtualbox-cpu-count=2 --virtualbox-boot2docker-url ~/Downloads/boot2docker.iso default
          docker-machine env default

      - name: Clone The Secret Mirror Repository
        run: |
          git clone https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.MIRROR_REPOSLUG }} source

      - name: Compile The Mirroring Docker Container
        run: |
          cd source || exit 1
          git checkout $BRANCH
          eval $(docker-machine env default)
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker container prune --force || true
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t mirror-bot
          docker image ls

      - name: Running mirror-bot In Docker
        timeout-minutes: 300
        continue-on-error: true
        run: |
          eval $(docker-machine env default)
          docker run --privileged --rm -i mirror-bot

      - name: Loop Workflow
        continue-on-error: true
        run: |
          # ${GITHUB_REPOSITORY} is the repo slug which runs this script
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          git add looper.txt
          git commit -m "Workflow : Loop at $(date -u +%D-%T%P)"
          git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
